// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/diagnostics.proto

package diagnostics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_diagnostics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnostics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_diagnostics_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_diagnostics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnostics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_diagnostics_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_diagnostics_proto protoreflect.FileDescriptor

const file_proto_diagnostics_proto_rawDesc = "" +
	"\n" +
	"\x17proto/diagnostics.proto\x12\vdiagnostics\"\a\n" +
	"\x05Empty\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2J\n" +
	"\x11PrismaDiagnostics\x125\n" +
	"\x04Ping\x12\x12.diagnostics.Empty\x1a\x19.diagnostics.PingResponseBDZBgithub.com/WelintonJunior/obd-diagnostic-service/proto;diagnosticsb\x06proto3"

var (
	file_proto_diagnostics_proto_rawDescOnce sync.Once
	file_proto_diagnostics_proto_rawDescData []byte
)

func file_proto_diagnostics_proto_rawDescGZIP() []byte {
	file_proto_diagnostics_proto_rawDescOnce.Do(func() {
		file_proto_diagnostics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_diagnostics_proto_rawDesc), len(file_proto_diagnostics_proto_rawDesc)))
	})
	return file_proto_diagnostics_proto_rawDescData
}

var file_proto_diagnostics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_diagnostics_proto_goTypes = []any{
	(*Empty)(nil),        // 0: diagnostics.Empty
	(*PingResponse)(nil), // 1: diagnostics.PingResponse
}
var file_proto_diagnostics_proto_depIdxs = []int32{
	0, // 0: diagnostics.PrismaDiagnostics.Ping:input_type -> diagnostics.Empty
	1, // 1: diagnostics.PrismaDiagnostics.Ping:output_type -> diagnostics.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_diagnostics_proto_init() }
func file_proto_diagnostics_proto_init() {
	if File_proto_diagnostics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_diagnostics_proto_rawDesc), len(file_proto_diagnostics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_diagnostics_proto_goTypes,
		DependencyIndexes: file_proto_diagnostics_proto_depIdxs,
		MessageInfos:      file_proto_diagnostics_proto_msgTypes,
	}.Build()
	File_proto_diagnostics_proto = out.File
	file_proto_diagnostics_proto_goTypes = nil
	file_proto_diagnostics_proto_depIdxs = nil
}
