// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/diagnostics.proto

package diagnostics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrismaDiagnostics_Ping_FullMethodName = "/diagnostics.PrismaDiagnostics/Ping"
)

// PrismaDiagnosticsClient is the client API for PrismaDiagnostics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrismaDiagnosticsClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
}

type prismaDiagnosticsClient struct {
	cc grpc.ClientConnInterface
}

func NewPrismaDiagnosticsClient(cc grpc.ClientConnInterface) PrismaDiagnosticsClient {
	return &prismaDiagnosticsClient{cc}
}

func (c *prismaDiagnosticsClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, PrismaDiagnostics_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrismaDiagnosticsServer is the server API for PrismaDiagnostics service.
// All implementations must embed UnimplementedPrismaDiagnosticsServer
// for forward compatibility.
type PrismaDiagnosticsServer interface {
	Ping(context.Context, *Empty) (*PingResponse, error)
	mustEmbedUnimplementedPrismaDiagnosticsServer()
}

// UnimplementedPrismaDiagnosticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrismaDiagnosticsServer struct{}

func (UnimplementedPrismaDiagnosticsServer) Ping(context.Context, *Empty) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPrismaDiagnosticsServer) mustEmbedUnimplementedPrismaDiagnosticsServer() {}
func (UnimplementedPrismaDiagnosticsServer) testEmbeddedByValue()                           {}

// UnsafePrismaDiagnosticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrismaDiagnosticsServer will
// result in compilation errors.
type UnsafePrismaDiagnosticsServer interface {
	mustEmbedUnimplementedPrismaDiagnosticsServer()
}

func RegisterPrismaDiagnosticsServer(s grpc.ServiceRegistrar, srv PrismaDiagnosticsServer) {
	// If the following call pancis, it indicates UnimplementedPrismaDiagnosticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrismaDiagnostics_ServiceDesc, srv)
}

func _PrismaDiagnostics_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismaDiagnosticsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismaDiagnostics_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismaDiagnosticsServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PrismaDiagnostics_ServiceDesc is the grpc.ServiceDesc for PrismaDiagnostics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrismaDiagnostics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diagnostics.PrismaDiagnostics",
	HandlerType: (*PrismaDiagnosticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PrismaDiagnostics_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/diagnostics.proto",
}
